#!/usr/bin/env python3

import shutil
import sys, os, time
from http.server import SimpleHTTPRequestHandler,BaseHTTPRequestHandler,ThreadingHTTPServer,HTTPServer
from threading import Thread
import json

# from PySide2.QtCore import (QUrl, Signal, Slot, QObject, QSize, Qt)
# from PySide2.QtGui import (QIcon,QPixmap)
# from PySide2.QtWidgets import (QApplication, QAction, QLineEdit, QMainWindow, QPushButton, QToolBar)
# from PySide2.QtWebEngineWidgets import (QWebEngineSettings, QWebEngineView, QWebEnginePage)

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from PySide2.QtWebEngineWidgets import *

import urllib3
import tarfile, tempfile

from jinja2 import Environment, FileSystemLoader

try:
    from bs4 import BeautifulSoup
except:
    pass


DEBUG=True
DEBUG_REQUESTS=True
FIXED_PORT=16666
USE_CACHE=False
LIBRARY_DIR='/usr/lib/simplayer'
IMAGE_DIR=f'{LIBRARY_DIR}/images'
TEMPLATE_DIR=f'{LIBRARY_DIR}/templates'
RESOURCE_DIR=f'{LIBRARY_DIR}/resources'
#FLASH_PPAPI_DIR=f'{LIBRARY_DIR}/untracked'
#FLASH_PPAPI_FILES=['libpepflashplayer.so','manifest.json']
#FLASH_PPAPI=f'{FLASH_PPAPI_DIR}/libpepflashplayer.so'

# def download_libs():
#     if os.path.isfile(FLASH_PPAPI):
#         return
#     url='http://ftp.eq.uc.pt/software/Linux/deb-multimedia/pool/non-free/p/pepper-flash-player/flashplayer-chromium_32.0.0.465-dmo1_amd64.deb'
#     try:
#         with tempfile.TemporaryDirectory() as tmpdir:
#             with urllib3.PoolManager().request('GET',url, preload_content=False) as fp1:
#                 with open(f'{tmpdir}/file.deb','wb') as fp2:
#                     shutil.copyfileobj(fp1,fp2)
#                     os.system(f'/usr/bin/ar x {tmpdir}/file.deb --output {tmpdir}')
#                     tar = tarfile.open(name=f'{tmpdir}/data.tar.xz',mode='r:xz')
#                     for member in (m for m in tar.getmembers() if m.isfile() and os.path.basename(m.name) in ['libpepflashplayer.so','manifest.json']):
#                         with open(f'{FLASH_PPAPI_DIR}/{os.path.basename(member.name)}','wb') as fp3:
#                             shutil.copyfileobj(tar.extractfile(member),fp3)
#             pass
#     except Exception as e:
#         print(f'{str(e)}')
#         pass

class Handler(SimpleHTTPRequestHandler):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,directory=LIBRARY_DIR,**kwargs)

    # def translate_path(self, path, *args):
    #     return super().translate_path(path, *args)

    def do_GET(self,*args):
        content = None
        basename = os.path.basename(self.path)
        if basename:
            if 'home?' == basename[:5]:
                key = basename.split('?')[1]
                if key:
                    if key == 'gltest=no':
                        self.server.http_server.webgl_detection.emit('NO')
                        self.server.tm.set_webgl_enabled(False)
                    else:
                        self.server.http_server.webgl_detection.emit('YES')
                    content = self.server.tm.get_html(type_html=key).encode('utf8')
            if 'swf?' == basename[:4]:
                key = basename.split('?')[1]
                content = self.server.tm.get_html(type_html='swf',name=key).encode('utf8')
            if 'webgl?' == basename[:6]:
                content = self.server.tm.check_webgl().encode('utf8')
        elif self.path == '/':
            content = self.server.tm.get_html(type_html='home').encode('utf8')

        if content:
            self.send_response(200)
            self.end_headers()
            self.wfile.write(content)
        else:
            try:
                super().do_GET(*args)
            except Exception as e:
                try:
                    self.send_error(429)
                except Exception as e2:
                    pass
                # print(f'Fail request {self.path}')

    # def list_directory(self, path):
    #     return super().list_directory(path)

    def log_message(self, format, *args):
        if DEBUG_REQUESTS:
            return super().log_message(format, *args)

class CustomTCPServer(ThreadingHTTPServer,QObject):
    def __init__(self,*args,**kwargs):
        self.http_server = kwargs.get('http_server')
        if self.http_server:
               kwargs.pop('http_server')
        super().__init__(*args,**kwargs)
        # self.spider = Spider()
        self.tm = TemplateManager()

class HttpServer(QObject):
    server_started = Signal(str)
    webgl_detection = Signal(str)

    def __init__(self):
        super().__init__()
        self.thread_server = Thread(target=self.start_server,name='http_server',daemon=True)
        self.thread_server.start()

    def start_server(self):
        while True:
            try:
                port = 0
                if FIXED_PORT:
                    port = FIXED_PORT
                with CustomTCPServer(("",port),Handler,http_server=self) as httpd:
                    p = httpd.server_address[1]
                    self.server_started.emit(str(p))
                    httpd.serve_forever()
            except Exception as e:
                pass

class TemplateManager():
    def __init__(self):
        self.webgl_enabled = True
        self.basedir = LIBRARY_DIR
        self.cache = {}
        self.loader = FileSystemLoader(searchpath=TEMPLATE_DIR)
        self.environment = Environment(loader=self.loader)
        self.projects = {}
        self.categories = {}
        self.search_projects()
        self.search_categories()

    def set_webgl_enabled(self,status):
        self.webgl_enabled=status
        self.cache = {}

    def search_projects(self):
        for x in (d for d in os.listdir(RESOURCE_DIR) if os.path.isdir(f'{RESOURCE_DIR}/{d}')):
            prj = f'{RESOURCE_DIR}/{x}'
            try:
                f = json.load(open(os.path.join(prj,'meta.json'),'r'))
                self.projects.setdefault(prj,f)
            except Exception as e:
                pass

    def search_categories(self):
        imagedir = f'{self.basedir}/images/categories'
        for x in (f for f in os.listdir(imagedir) if os.path.basename(f).split('.')[-1] == 'svg' and os.path.isfile(os.path.join(imagedir,f))):
            self.categories.setdefault(os.path.basename(x).split('.')[0],os.path.relpath(os.path.join(self.basedir,x),self.basedir))

    def get_html(self,*args,**kwargs):
        type_html = kwargs.get('type_html')
        show = 'home'
        if type_html and type_html in self.categories:
            show = type_html
        elif type_html == 'swf':
            name = kwargs.get('name')
            show = f'swf_{name}'

        out = None
        if USE_CACHE:
            out = self.cache.get(show)

        if out:
            return out
        if show == 'home':
            content = self.index_html()
        elif type_html == 'swf':
            content = self.swf_html(name=name)
        else:
            content = self.category_html(show=show)
        self.cache.setdefault(show,content)
        return content

    def check_webgl(self):
        tpl = self.environment.get_template('checkwebgl.tpl')
        content = tpl.render()
        return content

    def index_html(self):
        tpl = self.environment.get_template('index.tpl')
        items = [ (f'home?{k}',f'images/categories/{k}.svg',f'{k}') for k in sorted(self.categories.keys()) ]
        content = tpl.render(categories=items)
        return content

    def category_html(self,*args,**kwargs):
        category = kwargs.get('show')
        color = '#f5f5dc'
        if category == 'math':
            color = '#ff0000'
        elif category == 'earth-science':
            color = '#82553c'
        elif category == 'biology':
            color = '#00ff00'
        elif category == 'physics':
            color = '#0000ff'
        elif category == 'chemistry':
            color = '#820082'
        tpl = self.environment.get_template('categories.tpl')
        items = [ (f'{os.path.relpath(k,self.basedir)}/{v.get("html")}',f'{os.path.relpath(k,self.basedir)}/{v.get("banner")}',v.get('name')) for k,v in self.projects.items() if category in v.get('category').split(',') and ( (self.webgl_enabled == False and 'webgl' not in v.get('require')) or self.webgl_enabled )]
        content = tpl.render(items=items,color=color)
        return content

    def swf_html(self,*args,**kwargs):
        name = kwargs.get('name')
        if not name:
            return ''
        tpl = self.environment.get_template('swf.tpl')
        content = tpl.render(html={'rufflepath':'/ruffle/ruffle.js','swf':name})
        pass
        return content

class WebEngine(QWebEngineView):
    def __init__(self,*args,**kwargs):
        super(WebEngine,self).__init__(*args,**kwargs)
        self.initSettings()
        #print(f'Acceleration is : {self.checkSettings()}')

    # def checkSettings(self):
    #     pagesettings = QWebEngineSettings.globalSettings()
    #     setting = QWebEngineSettings.WebGLEnabled
    #     return pagesettings.testAttribute(setting)

    def initSettings(self):
        pagesettings = QWebEngineSettings.globalSettings()
        settings = [QWebEngineSettings.WebGLEnabled, QWebEngineSettings.Accelerated2dCanvasEnabled, QWebEngineSettings.PluginsEnabled]
        for s in settings:
            b = pagesettings.testAttribute(s)
            pagesettings.setAttribute(s,True)
            a = pagesettings.testAttribute(s)
            if b != a and DEBUG:
                print(f'{s} activated!')

class MainWindow(QMainWindow):
    server_started = Signal(str)

    def debug_history(self):
        # n=0
        # for x in self.history:
        #     s=''
        #     if n == self.history_index:
        #         s='*'
        #     print(f'{s}{n}: {x}')
        #     n+=1
        n=0
        h = self.webEngineView.history()
        cur = h.currentItemIndex()
        for x in h.items():
            s=""
            if h == cur:
                s="*"
            print(f'{s}{n}:{x.url().toString()}')
            n+=1

    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f'{LIBRARY_DIR}/resources/favicon.ico'))
        self.mapping = {
            'debug_gpu-flags' : "chrome://gpu",
            'debug_webgl-report' : 'http://webglreport.com/',
            'debug_flash-test1' : 'https://condor.depaul.edu/sjost/hci430/flash-examples/Examples1/Examples1.htm',
            'debug_flash-version' : 'http://embed-swf.org/flash-player-version.php',
            'debug_webgl-detect' : lambda: self.load_url(f'{self.get_docroot()}/webgl?'),
            # 'debug_download' : lambda : download_libs(),
            'debug_swf': lambda: self.load_url(f'{self.get_docroot()}/resources/diza/swf?diza.swf'),
            'debug_code' : lambda : self.webEngineView.page().toHtml(lambda x: print(BeautifulSoup(x,features="lxml").prettify()) or self.debug_history()),
            'debug_ruffle': 'https://ruffle.rs/demo/',
            'back' : lambda : self.load_back(),
            'forward': lambda : self.load_forward()
        }

        self.local_server_port = None
        # self.history = []
        # self.history_index = -1
        self.server = HttpServer()
        self.server.server_started.connect(self.set_local_port)
        self.server.webgl_detection.connect(self.set_webgl_detection)
        self.webgl_enabled = True

        self.setWindowTitle('Phet activities')
        self.objects = {}

        self.objects.setdefault('toolbar',QToolBar(self))
        self.addToolBar(self.objects.get('toolbar'))
        self.objects.get('toolbar').setFloatable(False)
        self.objects.get('toolbar').setMovable(False)

        for key in ['home','back','forward']:
            self.add_button(key=key)
        if DEBUG:
            spacer = QWidget()
            spacer.setSizePolicy(QSizePolicy.Expanding,QSizePolicy.Preferred)
            self.objects.get('toolbar').addWidget(spacer)
            for d in sorted((x for x in self.mapping if 'debug_' in x)):
                self.add_button(d)

        self.webEngineView = WebEngine(self)
        self.webEngineView.page().urlChanged.connect(self.urlChanged)
        self.webEngineView.page().loadFinished.connect(self.loadFinished)

        self.setCentralWidget(self.webEngineView)

    def add_button(self,key=None):
        if key:
            nameobject = f'button_{key}'
            toolbar = self.objects.get('toolbar')

            if nameobject in self.objects:
                print('Warning: {key} object already defined, can\'t add')
                return
            image = f'{IMAGE_DIR}/buttons/{key}.svg'
            icon = None
            if os.path.isfile(image):
                icon = QIcon(QPixmap(image))
            else:
                print(f'Warning: Missing image {image}')
                icon = self.style().standardIcon(QStyle.SP_DesktopIcon)
                toolbar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)

            if 'debug_' in key:
                key = key.split('debug_')[1]
                action = QAction(icon,key,toolbar)
                action.setData(f'debug_{key}')
            else:
                action = QAction(icon,key,toolbar)
                action.setData(key)

            action.triggered.connect(self.buttonPushed)
            self.objects.setdefault(nameobject,action)
            toolbar.addAction(action)

    @Slot(str)
    def buttonPushed(self,*args,**kwargs):
        try:
            who = kwargs.get('who')
            if not who:
                who=self.sender().data()
            destination = self.mapping.get(who)
            if isinstance(destination,type(lambda x:x)):
                destination()
            else:
                if destination:
                    self.load_url(QUrl(destination))
                else:
                    self.load_url(f'{self.get_docroot()}home?{who}')
        except Exception as e:
            pass

    @Slot(str)
    def set_local_port(self,port=None):
        if port is not None:
            self.local_server_port = port
        self.load_url(f'{self.get_docroot()}/webgl?')
        # self.buttonPushed(who='home')

    @Slot(str)
    def set_webgl_detection(self,status=None):
        if status == 'NO':
            self.webgl_enabled = False

    def get_docroot(self):
        if self.local_server_port:
            return f'http://localhost:{self.local_server_port}/'
        return None

    def load_back(self):
        # if self.history_index > 0:
        #     self.history_index-=1
        #     self.load_url(self.history[self.history_index])
        self.webEngineView.back()
        # self.webEngineView.page().triggerAction(QWebEnginePage.Back)


    def load_forward(self):
        # if self.history_index < len(self.history)-1:
        #     self.history_index+=1
        #     self.load_url(self.history[self.history_index])
        self.webEngineView.forward()
        # self.webEngineView.page().triggerAction(QWebEnginePage.Forward)

    def load_url(self,url):
        if not isinstance(url,QUrl):
            url = QUrl(url)
        scheme=url.scheme()
        url = QUrl(scheme+':'+os.path.normpath(url.toString(QUrl.FormattingOptions(QUrl.RemoveScheme))))
        if DEBUG:
            print(f'Loading url {url.toString()} {"Valid!" if url.isValid() else "Not valid!"}')
        self.webEngineView.load(url)

    # def load(self):
    #     url = QUrl.fromUserInput(self.addressLineEdit.text())
    #     if url.isValid():
    #         self.webEngineView.load(url)

    def loadFinished(self, status):
        pass

    def urlChanged(self, url):
        url_txt = url.toString()
        # current_history_url = '' if self.history_index == -1 else self.history[self.history_index].toString()

        self.objects.get('button_back').setEnabled(self.webEngineView.history().canGoBack())
        self.objects.get('button_forward').setEnabled(self.webEngineView.history().canGoForward())

        self.load_url(url)

        if DEBUG:
            print(f'URL changed {url_txt}')

        # if self.history_index == -1:
        #     self.history.append(url)
        #     self.history_index+=1
        # elif self.history_index < len(self.history)-1:
        #     if current_history_url != url_txt and url_txt != root_url:
        #         self.history = self.history[:self.history_index+1]
        #         self.history.append(url)
        #         self.history_index = len(self.history)-1
        # elif url_txt != root_url and url_txt != current_history_url:
        #     self.history.append(url)
        #     self.history_index+=1

        # if self.history_index == len(self.history)-1:
        #     if self.forwardButton.isEnabled():
        #         self.forwardButton.setEnabled(False)
        # elif not self.forwardButton.isEnabled():
        #     self.forwardButton.setEnabled(True)
        # if self.history_index > 0:
        #     if not self.backButton.isEnabled():
        #         self.backButton.setEnabled(True)
        # elif self.backButton.isEnabled():
        #     self.backButton.setEnabled(False)
        pass

if __name__ == '__main__':
    # QApplication.setAttribute(Qt.AA_UseOpenGLES,True)
    # QApplication.setAttribute(Qt.AA_UseSoftwareOpenGL,True)
    # QApplication.setAttribute(Qt.AA_ShareOpenGLContexts,True)
    # download_libs()
    # if os.path.isfile(FLASH_PPAPI):
    #     sys.argv.append('--no-sandbox')
    #     sys.argv.append(f'--ppapi-flash-path={FLASH_PPAPI}')
    #     sys.argv.append('--ppapi-flash-version=32.0.0.151')
    #     print('Running without sandbox, flash available')
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling,True)
    app = QApplication(sys.argv)
    mainWin = MainWindow()
    availableGeometry = mainWin.screen().availableGeometry()
    #mainWin.resize(availableGeometry.width() * 2 / 3, availableGeometry.height() * 2 / 3)
    mainWin.resize(1280,1024)
    mainWin.show()
    sys.exit(app.exec_())
